### ISSUE TITLE
for inspiration - scrollbars

### ISSUE THREAD

**Issue by cintaccs** [motss/app-datepicker#173]
### Description

I used 

```
/* width */
::-webkit-scrollbar {
    width: 10px;
    height: 10px;
}

/* Track */
::-webkit-scrollbar-track {
    background: white;
    border-left: 1px solid whitesmoke;
}

/* Handle */
::-webkit-scrollbar-thumb {
    background: whitesmoke;
    background: gainsboro;
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
    background: dimgray;
}
```

to get rid of the web effect of the scroll bars. I know it is only webkit / chrome / edge .. but ...

**Comment by motss** [comment]
Does it cover the UI on other OSes like Linux and Windows? I've yet to try this.

**Comment by cintaccs** [comment]
no it is ignored on FF e.g.
<img width="320" alt="Screenshot 2020-02-16 at 17 13 39" src="https://user-images.githubusercontent.com/4300051/74608230-b9999280-50df-11ea-81a5-21ccb13e6330.png">

and in chrome

<img width="322" alt="Screenshot 2020-02-16 at 17 13 55" src="https://user-images.githubusercontent.com/4300051/74608236-c322fa80-50df-11ea-984e-bb9b63e54104.png">


again the coloring can be discussed - but getting rid of the 90´s browserlook is generally appreciated :-)

**Comment by motss** [comment]
I decided to add this suggestion to mimic that of Android datepicker's scrollbar.

The following CSS works for all Webkit browsers and modern Firefox:

```css
.year-list-view__full-list {
  max-height: calc(48px * 7);
  overflow-y: auto;

  scrollbar-color: var(--app-datepicker-scrollbar-thumb-bg-color, rgba(0, 0, 0, .35)) rgba(0, 0, 0, 0);
  scrollbar-width: thin;
}
.year-list-view__full-list::-webkit-scrollbar {
  width: 8px;
  background-color: rgba(0, 0, 0, 0);
}
.year-list-view__full-list::-webkit-scrollbar-thumb {
  background-color: var(--app-datepicker-scrollbar-thumb-bg-color, rgba(0, 0, 0, .35));
  border-radius: 50px;
}
.year-list-view__full-list::-webkit-scrollbar-thumb:hover {
  background-color: var(--app-datepicker-scrollbar-thumb-hover-bg-color, rgba(0, 0, 0, .5));
}
```
