### ISSUE TITLE
Empty calendars in RTL mode

### ISSUE THREAD

**Issue by brownieboy** [motss/app-datepicker#190]
### Description
Calendars are empty in RTL (Right to Left) mode

### Expected outcome
Calendar should display dates, ideally in RTL order 

### Actual outcome
Calendar is empty

### Live Demo
Your official demo page at https://motss-app.web.app/demo/app-datepicker.html (see Steps to reproduce).

### Steps to reproduce
1. Go to the official demo page (see link above).
2. Using the browser's dev tools,  set `dir="rtl"` attribute on the `<body>` or `<html>` tags.  (See GIF example below.)

### Browsers Affected

- [X] Chrome/ Opera
- [X] Firefox
- [ ] Safari 10+
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge 12+
- [ ] IE 11

![upstream-app-datepicker-issue](https://user-images.githubusercontent.com/1781909/101868861-529b1c00-3bd2-11eb-97f0-dc54afe9555c.gif)

**Comment by brownieboy** [comment]
Issue seems to be with the element `<div part="calendars" class="calendars-container has-min-date">`.  It's way off to the left of where it should be when the page is in RTL mode.

The dev tools show this class applied to the element:

```css
.calendars-container {
    display: flex;
    justify-content: center;
    position: relative;
    top: 0px;
    left: calc(-100%);
    width: calc(300%);
    transform: translateZ(0px);
    will-change: transform;
    touch-action: pan-y;
}
```

By changing `left: calc(-100%);` to positive, i.e. `left: calc(100%);` the element moved back where it should be, and the calendar worked in RTL mode.  That change stuffs it up for LTR mode, of course!
